# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutBox(object):
    def setupUi(self, AboutBox):
        AboutBox.setObjectName("AboutBox")
        AboutBox.setWindowModality(QtCore.Qt.ApplicationModal)
        AboutBox.resize(300, 200)
        AboutBox.setMinimumSize(QtCore.QSize(300, 200))
        AboutBox.setMaximumSize(QtCore.QSize(300, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        AboutBox.setWindowIcon(icon)
        AboutBox.setModal(True)

        self.retranslateUi(AboutBox)
        QtCore.QMetaObject.connectSlotsByName(AboutBox)

    def retranslateUi(self, AboutBox):
        _translate = QtCore.QCoreApplication.translate
        AboutBox.setWindowTitle(_translate("AboutBox", "Über uns"))
