# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_document.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewDocumentDialog(object):
    def setupUi(self, NewDocumentDialog):
        NewDocumentDialog.setObjectName("NewDocumentDialog")
        NewDocumentDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NewDocumentDialog.resize(400, 300)
        NewDocumentDialog.setMinimumSize(QtCore.QSize(400, 300))
        NewDocumentDialog.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        NewDocumentDialog.setWindowIcon(icon)
        NewDocumentDialog.setSizeGripEnabled(False)
        NewDocumentDialog.setModal(True)

        self.retranslateUi(NewDocumentDialog)
        QtCore.QMetaObject.connectSlotsByName(NewDocumentDialog)

    def retranslateUi(self, NewDocumentDialog):
        _translate = QtCore.QCoreApplication.translate
        NewDocumentDialog.setWindowTitle(_translate("NewDocumentDialog", "Neues Dokument - Notensatz"))
